name: Update Top5 IP Files

on:
  schedule:
    - cron: "0 * * * *"   # 每小时跑一次（你可改）
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write   # 必须给写权限

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: |
        mkdir -p outputs
        python outputs/i.py

    - name: Commit and push if changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add outputs/*.txt

        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update Top5 IP files"
          git push
        fi
